name: Deploy to Staging

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy-staging:
    name: Build & Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Quarkus App
        run: ./mvnw clean package -DskipTests

      - name: Copy files to staging server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          source: target/squadmap-backend-1.0.0-SNAPSHOT-runner.jar
          target: /home/obivan/squadmap-deploy/

      - name: Restart service via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /home/obivan/squadmap-deploy
            docker compose down
            docker compose up -d --build
