name: Deploy to Staging

on:
  push:
    branches:
      - master

jobs:
  deploy-staging:
    name: Build & Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Quarkus App
        run: ./mvnw clean package -Dquarkus.package.type=uber-jar

      - name: Delete old JAR on staging
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            rm -f /home/obivan/squadmap-backend/target/squadmap-backend-1.0.0-SNAPSHOT-runner.jar

      - name: Copy JAR to staging server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_PORT }}
          source: target/squadmap-backend-1.0.0-SNAPSHOT-runner.jar
          target: /home/obivan/squadmap-backend/target/
          overwrite: true
          timeout: 30s
          command_timeout: 10m

      - name: Fix permissions and restart Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          port: ${{ secrets.STAGING_PORT }}
          script: |
            cd /home/obivan/squadmap-backend
            chown obivan:obivan ./target/squadmap-backend-1.0.0-SNAPSHOT-runner.jar
            chmod 755 ./target/squadmap-backend-1.0.0-SNAPSHOT-runner.jar
            docker compose down
            docker compose up -d --build
